services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-${SUBDOMAIN}.${DOMAIN_NAME}}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_LISTEN_ADDRESS=${N8N_LISTEN_ADDRESS:-0.0.0.0}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-https}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL:-info}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED:-true}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:-true}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL:-https://${N8N_HOST:-${SUBDOMAIN}.${DOMAIN_NAME}}}
      - VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API:-https://${N8N_HOST:-${SUBDOMAIN}.${DOMAIN_NAME}}}
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL:-https://${N8N_HOST:-${SUBDOMAIN}.${DOMAIN_NAME}}}
      - WEBHOOK_URL=${WEBHOOK_URL:-https://${N8N_HOST:-${SUBDOMAIN}.${DOMAIN_NAME}}/}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - my_network

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./evolution_instances:/evolution/instances
    networks:
      - my_network
    env_file:
      - .env
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - my_network
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - ./evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - my_network
    command:
      ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

networks:
  my_network:
    external: true

volumes:
  evolution_redis:
  postgres_data:
  evolution_store:
  evolution_instances:
  n8n_data:
    external: true
